### ISSUE TITLE
sock error

### ISSUE THREAD

**Issue by AlexSun98** [One-com/node-mocha-docker-postgres#6]
![image](https://user-images.githubusercontent.com/21162558/37135864-4de8cb3a-22f3-11e8-9c42-e7cc7e555c21.png)

**Comment by ndastur** [comment]
Getting exactly the same error. Any clues @gustavnikolaj ?

**Comment by gustavnikolaj** [comment]
`/var/run/docker.sock` is the unix socket that is used to communicate with dockers internal rest api. If it does not exist I would assume that docker is either not running or you're maybe running docker-machine and having the api located somewhere else (on a remote host).

I don't directly do any traffic to docker. It is all handled through https://www.npmjs.com/package/dockerode

Sorry for the late reply, but I have been busy and I haven't used this project myself for a long time.

If you want to dig in yourself and none of the initial steps work, I'd suggest trying to upgrade the dockerode package and see if the problem is a change in recent docker version.

**Comment by gustavnikolaj** [comment]
I have ran the tests without any errors locally, with the most recent version of docker. I have also updated dockerode to the latest version and the tests still pass. I published that in v1.0.1 of this package.

I just realized that this could probably also be because you are running docker on windows and use the Linux Subsystem for Windows - that would also mean that docker wouldn't have a socket there.

Either way, I think this is probably going to be a problem with dockerode and not this library.

**Comment by ndastur** [comment]
Thanks @gustavnikolaj . I am on OSX and it turns out the brew installation of Docker doesn't start the Deamon. Would you be happy for me to edit the README and send you a PR?

**Comment by gustavnikolaj** [comment]
@ndastur Yes! :-)

**Comment by gustavnikolaj** [comment]
@ndastur added a note of how to avoid this situation in the readme: #7
